// *********************************
// *********************************
// **** Vault Table
// *********************************
// *********************************

Table vault {
    vault_id int [PK, increment, NOT NULL]
    user_id int
    created_at timestamptz [NOT NULL, DEFAULT: `now()`]
    updated_at timestamptz [NOT NULL, DEFAULT: `now()`]
    Note: 'Table to hold vault objects belonging to a user'
}
Ref: vault.user_id - users.user_id [update: cascade, delete: cascade]


